{{- if not (eq (.Values.fluentBit).disabled "true") }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-fluent-bit
  labels:
    {{- include "default.labels" . | indent 4 }}
  annotations:
    deploymentTime: {{ now | date "02.01.2006 15:04:05" }}
data:
  fluent-bit.conf: |-
{{ tpl ( .Files.Get "files/fluent-bit/fluent-bit.conf" ) . | indent 4 }}
  parsers.conf: |-
{{ tpl ( .Files.Get "files/fluent-bit/parsers.conf" ) . | indent 4 }}

{{- end }}
---
